### ISSUE TITLE
Vertical layout broken on bottom bar

### ISSUE THREAD

**Issue by CPDigitalDarkroom** [CPDigitalDarkroom/Barmoji#17]
![GitHawk Upload by CPDigitalDarkroom](https://i.imgur.com/nGM7Ywl.jpg)

![GitHawk Upload by CPDigitalDarkroom](https://i.imgur.com/v7rawgL.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NSExceptional** [comment]
Ah, that's my bad. I can whip up a fix for that.

**Comment by NSExceptional** [comment]
This just occurred to me: vertical scrolling probably shouldn't be enabled for the bottom bar at all, since scrolling up is likely to trigger the home gesture.

As for actually fixing it... Vertical layout was easy to get working on the top because I just made the collection view the same height as the cells, so I didn't have to worry about spacing. That's clearly not the case on the bottom, where the collection view is very tall. I don't know if it was made that tall for a reason or not. If we can make it less tall, that's an easy fix. If not, things get complicated. I'm no collection view expert and I'm not sure what the best way to go about this would be.

My first thought is to just make the spacing really large on the bottom, but I'm having trouble figuring out how to keep the rows centered. Might involve some other offset of some kind somewhere else, like scroll view content insets or something

**Comment by CPDigitalDarkroom** [comment]
Disabling vertical scrolling for the bottom is the easiest fix like you said. Perhaps the best solution in general for this issue due to how easy it is to trigger the home gesture. 

The height of the collection view was increased for the larger swipe area at the top to reduce any home feature misfires.
