### ISSUE TITLE
"Replace predictive bar" broken in iOS 13

### ISSUE THREAD

**Issue by NSExceptional** [CPDigitalDarkroom/Barmoji#24]
Title

**Comment by jcarlosperez** [comment]
Fixed in version 2019.1~beta4. Will make the source available once out of beta. LMK if you need access to the betas and I'll get you hooked up @NSExceptional

**Comment by NSExceptional** [comment]
Yeah, I'd love that! You can reach me at my GitHub email, or on Twitter at this handle.

**Comment by NSExceptional** [comment]
While we're on the topic of the predictive bar, do you know how much work #21 would be?

**Comment by jcarlosperez** [comment]
The latest update includes a long-press gesture to switch between barmoji and the stock predictive views as a temporary fix. Any text entry basically triggers the predictions being updated so not sure if watching for the prediction list changes would be a better solution.

**Comment by NSExceptional** [comment]
Hey that works in the meantime! I'll see if I can find some way to tell if a special predictive suggestion is being made

**Comment by austinBurn** [comment]
Can I get a beta copy please? Love the tweak.

Regards,
Austin Burn

On Dec 6, 2019, at 11:19 AM, Juan Carlos Perez <notifications@github.com> wrote:

﻿

Fixed in version 2019.1~beta4. Will make the source available once out of beta. LMK if you need access to the betas and I'll get you hooked up @NSExceptional<https://github.com/NSExceptional>
